name: Build Beta Version of qui
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'code-with-quarkus/pom.xml'

      - name: compile
        working-directory: code-with-quarkus
        run: mvn -B package

      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}/code-with-quarkus/target
      - run: echo "🍏 This job's status is ${{ job.status }}."